services:
  web:
    build: .
    volumes:
      - .:/app
      # Keep these specific volume mounts, even if commenting out the rest.
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/var/media
    ports:
      - 8000:8000
