[project]
name = "techcity"
version = "2024.02"
requires-python = ">=3.12"
dependencies = [
    "Jinja2",
    "Markdown",
    "PyYAML",
    "pydantic",
    "python-dotenv",
    "python-frontmatter",
    "requests",
    "urllib3",
]

[project.scripts]
techcity = "techcity.cli:main"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = [
    # bandit: Use of `assert` detected
    "S101",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
