service: community
image: mblayman/techfrederick-community

servers:
  web:
    - 45.55.106.163
  worker:
    hosts:
      - 45.55.106.163
    cmd:
      # Don't waste time running the system checks.
      python /app/manage.py run_huey --skip-checks

proxy:
  app_port: 8000
  host: community.techfrederick.org
  ssl: true

registry:
  username: mblayman
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    ALLOWED_HOSTS: '*'
    DB_DIR: /var/db
    # Make sure we never accidentally set DEBUG to True for production.
    DEBUG: "False"
    PYTHONUNBUFFERED: "1"
    TIME_ZONE: America/New_York
  secret:
    - SECRET_KEY

aliases:
  shell: app exec --interactive --reuse "bash"
  ssh: server exec --interactive "bash"

volumes:
 - "/var/db:/var/db"
