service: community
image: mblayman/techfrederick-community

servers:
  web:
    - 45.55.106.163
  cron:
    hosts:
      - 45.55.106.163
    cmd:
      bash -c "cat config/crontab | crontab - && cron -f"

proxy:
  app_port: 8000
  host: community.mattlayman.com
  ssl: true

registry:
  username: mblayman
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    # FIXME: This should be updated when there is an actual host and not just an IP.
    # What does the value need to be for this work with the healthcheck?
    # What host does the healthcheck use in its request?
    ALLOWED_HOSTS: '*'
    DB_DIR: /var/db
    # Make sure we never accidentally set DEBUG to True for production.
    DEBUG: "False"
    PYTHONUNBUFFERED: "1"
    TIMEZONE: America/New_York
  secret:
    - SECRET_KEY

aliases:
  shell: app exec --interactive --reuse "bash"
  ssh: server exec --interactive "bash"

volumes:
 - "/var/db:/var/db"
