service: community
image: mblayman/techfrederick-community

servers:
  web:
    - 45.55.106.163
  worker:
    hosts:
      - 45.55.106.163
    cmd:
      # Don't waste time running the system checks.
      python /app/manage.py run_huey --skip-checks

proxy:
  app_port: 8000
  host: community.techfrederick.org
  ssl: true
  healthcheck:
    # The db migration might make the app take longer to boot up
    # so provide more time before failing the health check.
    timeout: 60


registry:
  username: mblayman
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    ALLOWED_HOSTS: '*'
    CSRF_TRUSTED_ORIGIN: 'https://community.techfrederick.org'
    DB_DIR: /var/db
    # Make sure we never accidentally set DEBUG to True for production.
    DEBUG: "False"
    MEDIA_ROOT: /var/media
    PYTHONUNBUFFERED: "1"
    # The Sentry DSN is not a secret. It can be used in browser contexts,
    # so it doesn't need to be hidden. We store it here rather than hardcoding
    # it so that local development will not trigger Sentry tracking accidentally.
    SENTRY_DSN: https://757e25a7c4e445e972d5febde9ff89a0@o4508175311962112.ingest.us.sentry.io/4508175314845696
    TIME_ZONE: America/New_York
  secret:
    - SECRET_KEY

aliases:
  shell: app exec --interactive --reuse "bash"
  ssh: server exec --interactive "bash"

volumes:
 - "/var/db:/var/db"
 - "/var/media:/var/media"
