# Generated by Django 5.1.1 on 2024-10-31 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("groups", "0003_alter_group_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recording_type",
                    models.CharField(
                        choices=[("YOUTUBE", "YouTube")],
                        help_text="The type of recording",
                        max_length=16,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the recording", max_length=256
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="A description of the recording"),
                ),
                ("url", models.URLField(help_text="The URL to the recording")),
                (
                    "external_playlist_id",
                    models.CharField(
                        help_text="The ID of the playlist on the platform"
                        " (i.e. list=<...> on YouTube)",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="The ID of the recording on the platform"
                        " (i.e. v=<...> on YouTube)",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Misc metadata about the recording"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="The event that was recorded",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The group that recorded the event",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.group",
                    ),
                ),
            ],
        ),
    ]
