# Generated by Django 5.1.1 on 2024-11-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_eventrecording"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrecording",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time the recording was published",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventrecording",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the recording on the platform"
                " (i.e. v=<...> on YouTube)",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventrecording",
            name="external_playlist_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the playlist on the platform"
                " (i.e. list=<...> on YouTube)",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventrecording",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Misc metadata about the recording"
            ),
        ),
    ]
