# Generated by Django 5.1.1 on 2024-09-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField()),
                ("url", models.URLField(max_length=256)),
                ("description", models.TextField()),
                ("teaser", models.TextField()),
                (
                    "color",
                    models.CharField(
                        help_text=(
                            "A theme color to use for display purposes. "
                            "Must be a Tailwind color like `blue-500`."
                        ),
                        max_length=32,
                    ),
                ),
                (
                    "event_source",
                    models.CharField(
                        help_text=(
                            "What is the source of event information for this group"
                        ),
                        max_length=16,
                    ),
                ),
                (
                    "event_source_id",
                    models.CharField(
                        help_text="An optional ID to use when checking an event source",
                        max_length=32,
                    ),
                ),
            ],
        ),
    ]
