# Generated by Django 5.1.1 on 2024-10-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="kind",
            field=models.CharField(
                db_index=True,
                default="unknown",
                help_text="The broad category of a group",
                max_length=16,
            ),
        ),
    ]
