# Generated by Django 5.1.1 on 2024-10-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_group_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="kind",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("community", "Community"),
                    ("nonprofit", "Nonprofit"),
                    ("company", "Company"),
                ],
                db_index=True,
                default="unknown",
                help_text="The broad category of a group",
                max_length=16,
            ),
        ),
    ]
