# Generated by Django 5.1.1 on 2024-11-02 02:34

from django.db import migrations, models

import techcity.groups.models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_alter_group_event_source_alter_group_event_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="card_image",
            field=models.FileField(
                default="",
                help_text="The small image format used when displaying a card",
                upload_to=techcity.groups.models.card_image_path,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="hero_image",
            field=models.FileField(
                default="",
                help_text="The large image format used when displaying the group detail page",  # noqa
                upload_to=techcity.groups.models.hero_image_path,
            ),
            preserve_default=False,
        ),
    ]
